#!/bin/sh

usage() {
	echo "Command: $0 <start/stop>"
	echo "Functionality: installs/removes the UART module."
}

#Check that one arguments has been provided
if [ ! $# -eq 1 ]
then
	usage
	exit 1
fi

if [ $1 = "start" ]
then
    echo "Installing uart_driver module"

	mode="644"
	# Look for wheel or use staff
	if grep -q '^staff:' /etc/group; then
		group="staff"
	else
		group="wheel"
	fi

	#
	# AESDCHAR
	#

	module_uart_driver="misc"
	device_uart_driver="uart_driver"

	# Install module
	insmod /lib/modules/4.14.40/extra/$device_uart_driver.ko || exit 1

	# Retrieve major number
	major=$(awk "\$2==\"$module_uart_driver\" {print \$1}" /proc/devices)
	if [ ! -z ${major} ]; then
		# Remove nodes and place them again with ownership and access privileges
		rm -f /dev/${device_uart_driver}
		mknod /dev/${device_uart_driver} c $major 0
		chgrp $group /dev/${device_uart_driver}
		chmod $mode  /dev/${device_uart_driver}
	else
		echo "No device found in /proc/devices for driver ${device_uart_driver} (this driver may not allocate a device)"
	fi
    
elif [ $1 = "stop" ]
then
    echo "Removing uart_driver module"

	# Invoke rmmod with all arguments we got
	module_uart_driver="uart_driver"
	device_uart_driver="uart_driver"
	rmmod $device_uart_driver || exit 1
	# Remove stale nodes
	rm -f /dev/${device_uart_driver}
    
fi