#!/bin/sh

usage() {
	echo "Command: $0 <start/stop>"
	echo "Functionality: installs/removes the aesdchar module."
}

#Check that one arguments has been provided
if [ ! $# -eq 1 ]
then
	usage
	exit 1
fi

if [ $1 = "start" ]
then
    echo "Installing Aesdchar module"

	mode="644"
	# Look for wheel or use staff
	if grep -q '^staff:' /etc/group; then
		group="staff"
	else
		group="wheel"
	fi

	#
	# AESDCHAR
	#

	module_aesdchar="aesdchar"
	device_aesdchar="aesdchar"

	# Install module
	insmod /lib/modules/5.15.18/extra/$module_aesdchar.ko || exit 1

	# Retrieve major number
	major=$(awk "\$2==\"$module_aesdchar\" {print \$1}" /proc/devices)
	if [ ! -z ${major} ]; then
		# Remove nodes and place them again with ownership and access privileges
		rm -f /dev/${device_aesdchar}
		mknod /dev/${device_aesdchar} c $major 0
		chgrp $group /dev/${device_aesdchar}
		chmod $mode  /dev/${device_aesdchar}
	else
		echo "No device found in /proc/devices for driver ${device_aesdchar} (this driver may not allocate a device)"
	fi
    
elif [ $1 = "stop" ]
then
    echo "Removing aesdchar module"

	# Invoke rmmod with all arguments we got
	module_aesdchar="aesdchar"
	device_aesdchar="aesdchar"
	rmmod $module_aesdchar || exit 1
	# Remove stale nodes
	rm -f /dev/${device_aesdchar}
    
fi