#!/bin/sh

usage() {
	echo "Command: $0 <start/stop>"
	echo "Functionality: installs/removes the UART module."
}

#Check that one arguments has been provided
if [ ! $# -eq 1 ]
then
	usage
	exit 1
fi

if [ $1 = "start" ]
then
    echo "Installing uart_driver module"

	mode="644"
	# Look for wheel or use staff
	if grep -q '^staff:' /etc/group; then
		group="staff"
	else
		group="wheel"
	fi

	#
	# AESDCHAR
	#

	module_uart_driver="misc"
	device_uart_driver="uart_driver"

	# Install module
	insmod /lib/modules/4.14.40/extra/uart_driver.ko || exit 1
    
elif [ $1 = "stop" ]
then
    echo "Removing uart_driver module"
	device_uart_driver="uart_driver"
	rmmod $device_uart_driver || exit 1
    
fi